/**
 * Tests for lib/logger.ts — pure exported functions only.
 *
 * Functions tested:
 *   shouldLog(level)              — level rank filtering
 *   makeRequestContext(userId?)   — generates a UUID-format requestId
 *   contextFromHeader(header, userId?) — uses or generates request context
 *   createTimer(label)            — high-resolution timer returning { end() }
 *   serializeError(err)           — serialize any caught value to structured log object
 *
 * The async log() function writes to Supabase RPC and is NOT tested here.
 *
 * Run with: npx vitest run tests/logger.test.ts
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import {
  makeRequestContext,
  contextFromHeader,
  shouldLog,
  createTimer,
  serializeError,
} from '../lib/logger'
import { AppError } from '../types/errors'

// ── UUID-like format helper ───────────────────────────────────────────────────
// requestId format generated by makeRequestContext:
//   xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx  (version 4-like, hex chars)
const UUID_LIKE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

// ── shouldLog ─────────────────────────────────────────────────────────────────

describe('shouldLog — level rank filtering', () => {
  // In test environment, NODE_ENV is 'test', so getConfiguredLevel() defaults
  // to 'debug' (same as non-production). We test relative ordering.

  it('debug >= debug → true (debug always logs at debug level)', () => {
    // When LOG_LEVEL is 'debug' (default in non-prod), debug should log
    const prevLogLevel = process.env.LOG_LEVEL
    process.env.LOG_LEVEL = 'debug'
    expect(shouldLog('debug')).toBe(true)
    process.env.LOG_LEVEL = prevLogLevel
  })

  it('info >= debug → true', () => {
    process.env.LOG_LEVEL = 'debug'
    expect(shouldLog('info')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('warn >= debug → true', () => {
    process.env.LOG_LEVEL = 'debug'
    expect(shouldLog('warn')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('error >= debug → true', () => {
    process.env.LOG_LEVEL = 'debug'
    expect(shouldLog('error')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('debug < info → false when LOG_LEVEL=info', () => {
    process.env.LOG_LEVEL = 'info'
    expect(shouldLog('debug')).toBe(false)
    delete process.env.LOG_LEVEL
  })

  it('info >= info → true when LOG_LEVEL=info', () => {
    process.env.LOG_LEVEL = 'info'
    expect(shouldLog('info')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('warn >= info → true when LOG_LEVEL=info', () => {
    process.env.LOG_LEVEL = 'info'
    expect(shouldLog('warn')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('debug < warn → false when LOG_LEVEL=warn', () => {
    process.env.LOG_LEVEL = 'warn'
    expect(shouldLog('debug')).toBe(false)
    delete process.env.LOG_LEVEL
  })

  it('info < warn → false when LOG_LEVEL=warn', () => {
    process.env.LOG_LEVEL = 'warn'
    expect(shouldLog('info')).toBe(false)
    delete process.env.LOG_LEVEL
  })

  it('error >= warn → true when LOG_LEVEL=warn', () => {
    process.env.LOG_LEVEL = 'warn'
    expect(shouldLog('error')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('only error passes when LOG_LEVEL=error', () => {
    process.env.LOG_LEVEL = 'error'
    expect(shouldLog('debug')).toBe(false)
    expect(shouldLog('info')).toBe(false)
    expect(shouldLog('warn')).toBe(false)
    expect(shouldLog('error')).toBe(true)
    delete process.env.LOG_LEVEL
  })

  it('returns boolean (not truthy/falsy)', () => {
    process.env.LOG_LEVEL = 'debug'
    const result = shouldLog('info')
    expect(typeof result).toBe('boolean')
    delete process.env.LOG_LEVEL
  })
})

// ── makeRequestContext ────────────────────────────────────────────────────────

describe('makeRequestContext — requestId generation', () => {
  it('returns an object with requestId and userId', () => {
    const ctx = makeRequestContext()
    expect(typeof ctx.requestId).toBe('string')
    expect('userId' in ctx).toBe(true)
  })

  it('requestId has length 36 (UUID format)', () => {
    const ctx = makeRequestContext()
    expect(ctx.requestId).toHaveLength(36)
  })

  it('requestId matches UUID-like pattern', () => {
    const ctx = makeRequestContext()
    expect(ctx.requestId).toMatch(UUID_LIKE)
  })

  it('defaults userId to null when not provided', () => {
    const ctx = makeRequestContext()
    expect(ctx.userId).toBeNull()
  })

  it('sets userId when provided', () => {
    const ctx = makeRequestContext('user-123')
    expect(ctx.userId).toBe('user-123')
  })

  it('generates unique requestIds on each call', () => {
    const ids = new Set(Array.from({ length: 20 }, () => makeRequestContext().requestId))
    expect(ids.size).toBe(20)
  })

  it('requestId always contains exactly 4 hyphens', () => {
    for (let i = 0; i < 10; i++) {
      const { requestId } = makeRequestContext()
      const hyphens = (requestId.match(/-/g) ?? []).length
      expect(hyphens).toBe(4)
    }
  })

  it('version nibble is always 4 (UUID v4-like)', () => {
    for (let i = 0; i < 20; i++) {
      const { requestId } = makeRequestContext()
      // Position 14 should be '4' (UUID v4 version)
      expect(requestId[14]).toBe('4')
    }
  })

  it('userId is preserved as-is when provided', () => {
    const ctx = makeRequestContext('auth0|abc123')
    expect(ctx.userId).toBe('auth0|abc123')
  })

  it('explicitly passing null gives null userId', () => {
    const ctx = makeRequestContext(null)
    expect(ctx.userId).toBeNull()
  })

  it('requestId contains only hex chars and hyphens', () => {
    const { requestId } = makeRequestContext()
    expect(requestId).toMatch(/^[0-9a-f-]+$/i)
  })

  it('generates different requestId on consecutive calls', () => {
    const a = makeRequestContext().requestId
    const b = makeRequestContext().requestId
    expect(a).not.toBe(b)
  })
})

// ── contextFromHeader ─────────────────────────────────────────────────────────

describe('contextFromHeader — header is a valid UUID', () => {
  it('uses the header value as requestId when valid', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId)
    expect(ctx.requestId).toBe(validId)
  })

  it('sets userId from parameter when header is valid', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId, 'user-xyz')
    expect(ctx.userId).toBe('user-xyz')
    expect(ctx.requestId).toBe(validId)
  })

  it('defaults userId to null when not passed', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId)
    expect(ctx.userId).toBeNull()
  })
})

describe('contextFromHeader — header is null or invalid', () => {
  it('generates a fresh context when header is null', () => {
    const ctx = contextFromHeader(null)
    expect(ctx.requestId).toHaveLength(36)
    expect(ctx.requestId).toMatch(UUID_LIKE)
  })

  it('generates a fresh context when header is empty string', () => {
    const ctx = contextFromHeader('')
    expect(ctx.requestId).toHaveLength(36)
  })

  it('generates a fresh context when header is too short', () => {
    const ctx = contextFromHeader('short-id')
    expect(ctx.requestId).not.toBe('short-id')
    expect(ctx.requestId).toHaveLength(36)
  })

  it('generates a fresh context when header has wrong format (letters only)', () => {
    const ctx = contextFromHeader('not-a-uuid-at-all-whatsoever-here')
    // 33 chars — may or may not match UUID length, but format check will fail
    expect(typeof ctx.requestId).toBe('string')
  })

  it('sets userId even when generating fresh context from null header', () => {
    const ctx = contextFromHeader(null, 'user-fallback')
    expect(ctx.userId).toBe('user-fallback')
  })

  it('null header → fresh requestId differs from any header value', () => {
    const ctx = contextFromHeader(null)
    expect(ctx.requestId).not.toBe('null')
    expect(ctx.requestId).not.toBe('')
  })

  it('fresh context from null header has valid UUID format', () => {
    for (let i = 0; i < 5; i++) {
      const ctx = contextFromHeader(null)
      expect(ctx.requestId).toMatch(UUID_LIKE)
    }
  })
})

describe('contextFromHeader — valid UUID regex boundary', () => {
  it('exactly 36-char hex UUID passes validation', () => {
    const id = '00000000-0000-4000-8000-000000000000'
    const ctx = contextFromHeader(id)
    expect(ctx.requestId).toBe(id)
  })

  it('UUID with uppercase letters passes validation (case-insensitive)', () => {
    const id = 'A0B1C2D3-E4F5-4678-9ABC-DEF012345678'
    const ctx = contextFromHeader(id)
    expect(ctx.requestId).toBe(id)
  })

  it('37-char string does not pass (too long)', () => {
    // Extra char at end
    const tooLong = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890X'
    const ctx = contextFromHeader(tooLong)
    // Should generate fresh, not use the invalid header
    expect(ctx.requestId).not.toBe(tooLong)
  })

  it('35-char string does not pass (too short)', () => {
    const tooShort = 'a1b2c3d4-e5f6-4789-abcd-ef123456789'
    const ctx = contextFromHeader(tooShort)
    expect(ctx.requestId).not.toBe(tooShort)
    expect(ctx.requestId).toHaveLength(36)
  })

  it('UUID with invalid chars in wrong positions returns fresh id', () => {
    // g is not a valid hex char
    const badHex = 'g1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(badHex)
    expect(ctx.requestId).not.toBe(badHex)
  })
})

// ── createTimer ───────────────────────────────────────────────────────────────

describe('createTimer — performance timing helper', () => {
  it('returns an object with an end() method', () => {
    const timer = createTimer('test-label')
    expect(typeof timer.end).toBe('function')
  })

  it('end() can be called without arguments', () => {
    const timer = createTimer('test')
    expect(() => timer.end()).not.toThrow()
  })

  it('end() can be called with metadata', () => {
    const timer = createTimer('test')
    expect(() => timer.end({ key: 'value', count: 42 })).not.toThrow()
  })

  it('end() logs to console.info', () => {
    const spy = vi.spyOn(console, 'info').mockImplementation(() => {})
    const timer = createTimer('my-label')
    timer.end()
    expect(spy).toHaveBeenCalledOnce()
    spy.mockRestore()
  })

  it('logged entry contains label in message', () => {
    let loggedStr = ''
    const spy = vi.spyOn(console, 'info').mockImplementation((s: string) => { loggedStr = s })
    const timer = createTimer('my-operation')
    timer.end()
    spy.mockRestore()
    const parsed = JSON.parse(loggedStr)
    expect(parsed.message).toContain('my-operation')
  })

  it('logged entry contains duration_ms as a number', () => {
    let loggedStr = ''
    const spy = vi.spyOn(console, 'info').mockImplementation((s: string) => { loggedStr = s })
    const timer = createTimer('timing-test')
    timer.end()
    spy.mockRestore()
    const parsed = JSON.parse(loggedStr)
    expect(typeof parsed.duration_ms).toBe('number')
    expect(parsed.duration_ms).toBeGreaterThanOrEqual(0)
  })

  it('logged entry level is always "info"', () => {
    let loggedStr = ''
    const spy = vi.spyOn(console, 'info').mockImplementation((s: string) => { loggedStr = s })
    const timer = createTimer('any-label')
    timer.end()
    spy.mockRestore()
    const parsed = JSON.parse(loggedStr)
    expect(parsed.level).toBe('info')
  })

  it('metadata is merged into logged entry', () => {
    let loggedStr = ''
    const spy = vi.spyOn(console, 'info').mockImplementation((s: string) => { loggedStr = s })
    const timer = createTimer('meta-test')
    timer.end({ rows_affected: 7 })
    spy.mockRestore()
    const parsed = JSON.parse(loggedStr)
    expect(parsed.rows_affected).toBe(7)
  })

  it('message contains "completed" suffix', () => {
    let loggedStr = ''
    const spy = vi.spyOn(console, 'info').mockImplementation((s: string) => { loggedStr = s })
    const timer = createTimer('db-query')
    timer.end()
    spy.mockRestore()
    const parsed = JSON.parse(loggedStr)
    expect(parsed.message).toContain('completed')
  })
})

// ── serializeError ────────────────────────────────────────────────────────────

describe('serializeError — AppError handling', () => {
  it('extracts message from AppError', () => {
    const err = new AppError('INSUFFICIENT_STOCK', 'Stok yetersiz')
    const result = serializeError(err)
    expect(result.message).toBe('Stok yetersiz')
  })

  it('extracts code from AppError', () => {
    const err = new AppError('INSUFFICIENT_STOCK', 'Stok yetersiz')
    const result = serializeError(err)
    expect(result.code).toBe('INSUFFICIENT_STOCK')
  })

  it('includes stack for AppError (truncated to 500 chars)', () => {
    const err = new AppError('INVALID_PRICE', 'Geçersiz fiyat')
    const result = serializeError(err)
    // stack may be present (V8 environments have it)
    if (result.stack !== undefined) {
      expect(result.stack.length).toBeLessThanOrEqual(500)
    }
  })

  it('result has message and code properties for AppError', () => {
    const err = new AppError('NO_ITEMS', 'Kalem yok')
    const result = serializeError(err)
    expect('message' in result).toBe(true)
    expect('code' in result).toBe(true)
  })
})

describe('serializeError — native Error handling', () => {
  it('extracts message from native Error', () => {
    const err = new Error('something went wrong')
    const result = serializeError(err)
    expect(result.message).toBe('something went wrong')
  })

  it('does not include code for native Error', () => {
    const err = new Error('native error')
    const result = serializeError(err)
    expect(result.code).toBeUndefined()
  })

  it('includes stack for native Error (truncated)', () => {
    const err = new Error('test')
    const result = serializeError(err)
    if (result.stack !== undefined) {
      expect(result.stack.length).toBeLessThanOrEqual(500)
      expect(result.stack).toContain('Error')
    }
  })

  it('handles TypeError', () => {
    const err = new TypeError('type mismatch')
    const result = serializeError(err)
    expect(result.message).toBe('type mismatch')
  })

  it('handles RangeError', () => {
    const err = new RangeError('out of range')
    const result = serializeError(err)
    expect(result.message).toBe('out of range')
  })
})

describe('serializeError — string handling', () => {
  it('wraps plain string as message', () => {
    const result = serializeError('simple error string')
    expect(result.message).toBe('simple error string')
  })

  it('does not include code for plain string', () => {
    const result = serializeError('error')
    expect(result.code).toBeUndefined()
  })

  it('empty string → message is empty string', () => {
    const result = serializeError('')
    expect(result.message).toBe('')
  })
})

describe('serializeError — plain object handling', () => {
  it('extracts message from plain object with message property', () => {
    const result = serializeError({ message: 'object error', code: 'ERR_CODE' })
    expect(result.message).toBe('object error')
  })

  it('extracts code from plain object with code property', () => {
    const result = serializeError({ message: 'object error', code: 'ERR_CODE' })
    expect(result.code).toBe('ERR_CODE')
  })

  it('falls back to JSON.stringify when no message property', () => {
    const result = serializeError({ foo: 'bar' })
    expect(result.message).toContain('foo')
  })

  it('handles object with undefined code → no code in result', () => {
    const result = serializeError({ message: 'test' })
    expect(result.code).toBeUndefined()
  })
})

describe('serializeError — primitive and null handling', () => {
  it('serializes number to string message', () => {
    const result = serializeError(42)
    expect(result.message).toBe('42')
  })

  it('serializes null to "null" string', () => {
    const result = serializeError(null)
    expect(result.message).toBe('null')
  })

  it('serializes undefined to "undefined" string', () => {
    const result = serializeError(undefined)
    expect(result.message).toBe('undefined')
  })

  it('serializes false to "false" string', () => {
    const result = serializeError(false)
    expect(result.message).toBe('false')
  })

  it('always returns an object with at least a message property', () => {
    const inputs = [42, null, undefined, false, 'str', { message: 'x' }]
    for (const input of inputs) {
      const result = serializeError(input)
      expect(typeof result.message).toBe('string')
    }
  })
})

// ── Cross-function: makeRequestContext + contextFromHeader ────────────────────

describe('Cross-function consistency: makeRequestContext + contextFromHeader', () => {
  it('contextFromHeader with fresh-generated id === makeRequestContext format', () => {
    const fresh = contextFromHeader(null)
    expect(fresh.requestId).toMatch(UUID_LIKE)
    expect(fresh.requestId).toHaveLength(36)
  })

  it('contextFromHeader with makeRequestContext output → uses the generated id', () => {
    const ctx = makeRequestContext('user-a')
    const ctx2 = contextFromHeader(ctx.requestId, 'user-b')
    // Should reuse the same requestId since it passes validation
    expect(ctx2.requestId).toBe(ctx.requestId)
    expect(ctx2.userId).toBe('user-b')
  })

  it('two consecutive makeRequestContext calls produce different requestIds', () => {
    const a = makeRequestContext().requestId
    const b = makeRequestContext().requestId
    expect(a).not.toBe(b)
  })
})
