/**
 * Tests for lib/logger.ts — pure exported functions only.
 *
 * Two functions are testable without DB:
 *   makeRequestContext(userId?)  — generates a UUID-format requestId
 *   contextFromHeader(header, userId?) — uses or generates request context
 *
 * The async log() function writes to Supabase RPC and is NOT tested here.
 *
 * Run with: npx vitest run tests/logger.test.ts
 */
import { describe, it, expect } from 'vitest'
import { makeRequestContext, contextFromHeader } from '../lib/logger'

// ── UUID-like format helper ───────────────────────────────────────────────────
// requestId format generated by makeRequestContext:
//   xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx  (version 4-like, hex chars)
const UUID_LIKE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

// ── makeRequestContext ────────────────────────────────────────────────────────

describe('makeRequestContext — requestId generation', () => {
  it('returns an object with requestId and userId', () => {
    const ctx = makeRequestContext()
    expect(typeof ctx.requestId).toBe('string')
    expect('userId' in ctx).toBe(true)
  })

  it('requestId has length 36 (UUID format)', () => {
    const ctx = makeRequestContext()
    expect(ctx.requestId).toHaveLength(36)
  })

  it('requestId matches UUID-like pattern', () => {
    const ctx = makeRequestContext()
    expect(ctx.requestId).toMatch(UUID_LIKE)
  })

  it('defaults userId to null when not provided', () => {
    const ctx = makeRequestContext()
    expect(ctx.userId).toBeNull()
  })

  it('sets userId when provided', () => {
    const ctx = makeRequestContext('user-123')
    expect(ctx.userId).toBe('user-123')
  })

  it('generates unique requestIds on each call', () => {
    const ids = new Set(Array.from({ length: 20 }, () => makeRequestContext().requestId))
    expect(ids.size).toBe(20)
  })

  it('requestId always contains exactly 4 hyphens', () => {
    for (let i = 0; i < 10; i++) {
      const { requestId } = makeRequestContext()
      const hyphens = (requestId.match(/-/g) ?? []).length
      expect(hyphens).toBe(4)
    }
  })

  it('version nibble is always 4 (UUID v4-like)', () => {
    for (let i = 0; i < 20; i++) {
      const { requestId } = makeRequestContext()
      // Position 14 should be '4' (UUID v4 version)
      expect(requestId[14]).toBe('4')
    }
  })
})

// ── contextFromHeader ─────────────────────────────────────────────────────────

describe('contextFromHeader — header is a valid UUID', () => {
  it('uses the header value as requestId when valid', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId)
    expect(ctx.requestId).toBe(validId)
  })

  it('sets userId from parameter when header is valid', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId, 'user-xyz')
    expect(ctx.userId).toBe('user-xyz')
    expect(ctx.requestId).toBe(validId)
  })

  it('defaults userId to null when not passed', () => {
    const validId = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890'
    const ctx = contextFromHeader(validId)
    expect(ctx.userId).toBeNull()
  })
})

describe('contextFromHeader — header is null or invalid', () => {
  it('generates a fresh context when header is null', () => {
    const ctx = contextFromHeader(null)
    expect(ctx.requestId).toHaveLength(36)
    expect(ctx.requestId).toMatch(UUID_LIKE)
  })

  it('generates a fresh context when header is empty string', () => {
    const ctx = contextFromHeader('')
    expect(ctx.requestId).toHaveLength(36)
  })

  it('generates a fresh context when header is too short', () => {
    const ctx = contextFromHeader('short-id')
    expect(ctx.requestId).not.toBe('short-id')
    expect(ctx.requestId).toHaveLength(36)
  })

  it('generates a fresh context when header has wrong format (letters only)', () => {
    const ctx = contextFromHeader('not-a-uuid-at-all-whatsoever-here')
    // 33 chars — may or may not match UUID length, but format check will fail
    expect(typeof ctx.requestId).toBe('string')
  })

  it('sets userId even when generating fresh context from null header', () => {
    const ctx = contextFromHeader(null, 'user-fallback')
    expect(ctx.userId).toBe('user-fallback')
  })

  it('null header → fresh requestId differs from any header value', () => {
    const ctx = contextFromHeader(null)
    expect(ctx.requestId).not.toBe('null')
    expect(ctx.requestId).not.toBe('')
  })
})

describe('contextFromHeader — valid UUID regex boundary', () => {
  it('exactly 36-char hex UUID passes validation', () => {
    const id = '00000000-0000-4000-8000-000000000000'
    const ctx = contextFromHeader(id)
    expect(ctx.requestId).toBe(id)
  })

  it('UUID with uppercase letters passes validation (case-insensitive)', () => {
    const id = 'A0B1C2D3-E4F5-4678-9ABC-DEF012345678'
    const ctx = contextFromHeader(id)
    expect(ctx.requestId).toBe(id)
  })

  it('37-char string does not pass (too long)', () => {
    // Extra char at end
    const tooLong = 'a1b2c3d4-e5f6-4789-abcd-ef1234567890X'
    const ctx = contextFromHeader(tooLong)
    // Should generate fresh, not use the invalid header
    expect(ctx.requestId).not.toBe(tooLong)
  })
})
