-- migrate:up
-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 0 / TA.4 prep: Add voucher_number to journal_entries
--
-- Voucher numbers give auditors a stable, human-readable reference.
-- Format: JE-{YYYY}-{NNNNN}  (e.g. JE-2026-00142)
-- Auto-generated by trigger on INSERT.
-- The sequence is global (not per-company) for simplicity; gaps are acceptable.
-- ─────────────────────────────────────────────────────────────────────────────

-- Global sequence for voucher numbers
CREATE SEQUENCE IF NOT EXISTS journal_voucher_seq START 1;

-- Column (unique across platform — each entry has a unique voucher)
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS voucher_number text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_journal_entries_voucher
  ON journal_entries (voucher_number)
  WHERE voucher_number IS NOT NULL;

-- Trigger function: stamp voucher_number before INSERT
CREATE OR REPLACE FUNCTION fn_set_journal_voucher_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.voucher_number IS NULL THEN
    NEW.voucher_number := 'JE-' ||
      to_char(COALESCE(NEW.entry_date, CURRENT_DATE), 'YYYY') || '-' ||
      LPAD(nextval('journal_voucher_seq')::text, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_journal_voucher_number
  BEFORE INSERT ON journal_entries
  FOR EACH ROW EXECUTE FUNCTION fn_set_journal_voucher_number();

COMMENT ON COLUMN journal_entries.voucher_number IS
  'Stable human-readable reference (JE-YYYY-NNNNN). Auto-generated on insert.';

-- migrate:down
DROP TRIGGER IF EXISTS trg_journal_voucher_number ON journal_entries;
DROP FUNCTION IF EXISTS fn_set_journal_voucher_number();
DROP INDEX IF EXISTS idx_journal_entries_voucher;
ALTER TABLE journal_entries DROP COLUMN IF EXISTS voucher_number;
DROP SEQUENCE IF EXISTS journal_voucher_seq;
